FROM elixir:1.16-alpine

# Install git, build tools, sqlite, nodejs, and npm
RUN apk add --no-cache build-base neovim tmux openssh-client bash git sqlite nodejs npm inotify-tools

# Install Hex and Rebar
RUN mix local.hex --force && \
    mix local.rebar --force

RUN mkdir -p /root/.ssh && chmod 700 /root/.ssh
RUN ssh-keyscan github.com >> /root/.ssh/known_hosts

WORKDIR /app/repos
ARG REPO
# git@github.com:vishaldpatel/vishal_rs.git
RUN --mount=type=ssh \
  if [  -z $REPO ];then \
    echo "Git REPO has not beeen passed in as --build-arg." ;\
    echo "Creating repo free container..." ;\
  else \
    git clone $REPO ;\
  fi

